name: CI
on:
  push:
      branches:
        - "main"
  pull_request:
jobs:
  generateTOC:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:

          CHECK_ONLY_DEFAULT_BRANCH: true
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/main' }}

    needs:
      - generateTOC
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: bare
